version: '3'

services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    container_name: $CONTAINER_NAME
    ports:
      - '8090:8080'
      - '50000:50000'
    volumes:
      - $MOUNT_PATH:/var/jenkins_home