version: '3.1'

services:
  mysql:
    build:
      context: ./environment
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - EUREKA_SERVICE_HOST=${EUREKA_SERVICE_HOST}
    image: "${MYSQL_IMAGE_NAME}:${MYSQL_IMAGE_TAR}"
    restart: always
    container_name: "${MYSQL_CONTAINER_NAME}"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
